### ISSUE TITLE
Side menu on mobile is opened by default

### ISSUE THREAD

**Issue by beeman** [eggheadio/egghead-ui#150] opened 2017-05-04 22:15 UTC
The side menu on mobile is opened by default whereas before it was closed.

Probably related to #149, which makes the viewport larger than expected. 

![image uploaded from ios](https://cloud.githubusercontent.com/assets/36491/25727078/df7ce5e4-30ec-11e7-94e8-642a799d9bc4.jpg)

**Comment by trevordmiller** [comment] 2017-05-05 16:55
Thank you for the issue @beeman; will look into this.

**Comment by trevordmiller** [comment] 2017-05-09 20:45
Not related to 149, but I know what the problem is. In progress.

**Comment by trevordmiller** [comment] 2017-05-09 21:02
Waiting for [the latest egghead-ui PR](https://github.com/eggheadio/egghead-ui/pull/157) to be approved and merged so I can upgrade the egghead-instructor-center and fix this.

**Comment by trevordmiller** [comment] 2017-05-10 19:34
@beeman This has been fixed and will go out in the next release:
![responsive-navigation](https://cloud.githubusercontent.com/assets/5497885/25917452/549a7f8e-3585-11e7-9220-afdd9ee1650b.gif)

Thanks for your help!

**Comment by beeman** [comment] 2017-05-10 20:18
Thanks for fixing it so fast @trevordmiller 👍

**Comment by trevordmiller** [comment] 2017-05-10 21:35
@beeman No problem. Appreciate your issue; it's been released to prod: https://instructor.egghead.io/.

If you are interested in contributing in the future, I'd like to set up a test account for you:
https://github.com/eggheadio/egghead-ui/issues/152

**Closed as completed by trevordmiller** 2017-05-10 21:35 UTC
Labels: bug, component, app

**Comment by beeman** [comment] 2017-05-10 21:54
@trevordmiller just confirmed that both issues are fixed!  

I'm interested in that for sure.
